export interface Spec {
  label: string;
  value: string;
}

export interface SpotlightProduct {
  id: string;
  name: string;
  tagline: string;
  heroImage: string;
  accentColor: string;
  specs: Spec[];
  ctaLink: string;
}

export interface CatalogProduct {
  slug: string;
  categorySlug: string;
  name: string;
  tagline: string;
  description: string;
  heroImage: string;
  gallery: string[];
  accentColor: string;
  specs: Spec[];
  features: string[];
}

export const catalogProducts: CatalogProduct[] = [
  {
    slug: 'dual-motor-e-scooter',
    categorySlug: 'scooter',
    name: 'Dual Motor E-Scooter',
    tagline: 'Built for roads that push back.',
    description: 'A high-torque urban ride with long-range confidence, designed for daily movement and tougher streets.',
    heroImage: '/products/scooter/1hero.png',
    gallery: [
      '/products/scooter/1hero.png',
      '/products/scooter/alternate.png',
      '/products/scooter/detail.png',
      '/products/scooter/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Drive System', value: 'Dual Motor' },
      { label: 'Range', value: 'Up to 65 km' },
      { label: 'Frame', value: 'Foldable Alloy' },
      { label: 'Terrain', value: 'Off-Road Tires' },
    ],
    features: [
      'Stable daily commuting geometry',
      'Responsive acceleration and braking',
      'Foldable frame for easier storage',
      'Made for city use and rougher routes',
    ],
  },
  {
    slug: 'city-ride',
    categorySlug: 'scooter',
    name: 'City Ride',
    tagline: 'Lightweight movement for everyday trips.',
    description: 'A smoother, lighter take on electric commuting with a focus on maneuverability and convenience.',
    heroImage: '/products/scooter/alternate.png',
    gallery: [
      '/products/scooter/alternate.png',
      '/products/scooter/detail.png',
      '/products/scooter/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Ride Style', value: 'Urban' },
      { label: 'Portability', value: 'Easy Fold' },
      { label: 'Frame', value: 'Alloy Build' },
      { label: 'Use Case', value: 'Daily Commute' },
    ],
    features: [
      'Compact and practical for city life',
      'Comfort-focused riding position',
      'Quick to store and move',
      'Ideal for short-to-medium trips',
    ],
  },
  {
    slug: 'scooter-detail',
    categorySlug: 'scooter',
    name: 'Scooter Detail View',
    tagline: 'Close-up performance and design.',
    description: 'A product-first presentation of the scooter with an emphasis on details, materials, and finish.',
    heroImage: '/products/scooter/detail.png',
    gallery: [
      '/products/scooter/detail.png',
      '/products/scooter/1hero.png',
      '/products/scooter/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Focus', value: 'Build Quality' },
      { label: 'Finish', value: 'Matte / Gloss Mix' },
      { label: 'Visibility', value: 'Front Lighting' },
      { label: 'Ride Feel', value: 'Balanced' },
    ],
    features: [
      'Built around premium materials',
      'Easy-to-read detail presentation',
      'Focuses on the product’s physical design',
      'Strong visual language for product pages',
    ],
  },
  {
    slug: 'scooter-lifestyle',
    categorySlug: 'scooter',
    name: 'Scooter Lifestyle',
    tagline: 'See it in motion, in real life.',
    description: 'Lifestyle imagery that shows how the scooter fits into everyday routes, errands, and weekend rides.',
    heroImage: '/products/scooter/lifestyle.png',
    gallery: [
      '/products/scooter/lifestyle.png',
      '/products/scooter/alternate.png',
      '/products/scooter/1hero.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Context', value: 'Everyday Use' },
      { label: 'Mobility', value: 'Flexible' },
      { label: 'Style', value: 'Modern' },
      { label: 'Audience', value: 'Urban Riders' },
    ],
    features: [
      'Designed to look natural in real usage',
      'Strong for marketing and social content',
      'Highlights scale and practical use',
      'Good for showing the ride experience',
    ],
  },
  {
    slug: 'rgb-speaker',
    categorySlug: 'speaker',
    name: 'RGB Speaker',
    tagline: 'Sound that moves. Light that breathes.',
    description: 'A portable speaker with bold lighting, immersive sound, and a party-ready look.',
    heroImage: '/products/speaker/hero.png',
    gallery: [
      '/products/speaker/hero.png',
      '/products/speaker/alternate.png',
      '/products/speaker/detail.png',
      '/products/speaker/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Sound Stage', value: '360° Surround' },
      { label: 'RGB Ring', value: '16M Colour' },
      { label: 'Battery', value: '24-Hour Playback' },
      { label: 'Connectivity', value: 'Bluetooth 5.3' },
    ],
    features: [
      'Made for music, events, and casual listening',
      'Bold RGB styling with a premium look',
      'Portable body for easy movement',
      'Strong hero visuals for product pages',
    ],
  },
  {
    slug: 'speaker-alternate-angle',
    categorySlug: 'speaker',
    name: 'Speaker Alternate Angle',
    tagline: 'A different view of the same energy.',
    description: 'An alternate presentation of the speaker designed to showcase shape, lighting, and surface texture.',
    heroImage: '/products/speaker/alternate.png',
    gallery: [
      '/products/speaker/alternate.png',
      '/products/speaker/hero.png',
      '/products/speaker/detail.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Focus', value: 'Profile View' },
      { label: 'Lighting', value: 'RGB Accent' },
      { label: 'Use', value: 'Marketing' },
      { label: 'Style', value: 'Premium' },
    ],
    features: [
      'Good for alternate marketing creatives',
      'Highlights silhouette and form',
      'Supports multi-angle storytelling',
      'Matches the main speaker identity',
    ],
  },
  {
    slug: 'speaker-detail-close-up',
    categorySlug: 'speaker',
    name: 'Speaker Detail Close-up',
    tagline: 'A closer look at the finish.',
    description: 'A detail-focused product page for showing texture, controls, and physical build quality.',
    heroImage: '/products/speaker/detail.png',
    gallery: [
      '/products/speaker/detail.png',
      '/products/speaker/hero.png',
      '/products/speaker/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Focus', value: 'Surface Detail' },
      { label: 'Buttons', value: 'Tactile Controls' },
      { label: 'Output', value: 'Loud & Clear' },
      { label: 'Style', value: 'Close-up' },
    ],
    features: [
      'Excellent for feature callouts',
      'Brings attention to product finish',
      'Ideal for ecommerce detail pages',
      'Pairs well with specification blocks',
    ],
  },
  {
    slug: 'speaker-in-use',
    categorySlug: 'speaker',
    name: 'Speaker In Use',
    tagline: 'How it feels in real life.',
    description: 'Lifestyle imagery that places the speaker in real environments to help customers imagine ownership.',
    heroImage: '/products/speaker/lifestyle.png',
    gallery: [
      '/products/speaker/lifestyle.png',
      '/products/speaker/hero.png',
      '/products/speaker/alternate.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Context', value: 'Lifestyle' },
      { label: 'Mood', value: 'Energetic' },
      { label: 'Audience', value: 'Music Lovers' },
      { label: 'Format', value: 'Hero Scene' },
    ],
    features: [
      'Shows the product in everyday situations',
      'Useful for ads and social content',
      'Supports stronger conversion storytelling',
      'Keeps the speaker visually exciting',
    ],
  },
  {
    slug: 'portable-power-station',
    categorySlug: 'power-station',
    name: 'Portable Power Station',
    tagline: 'The grid, untethered.',
    description: 'Compact backup power for travel, work, and outages, with a strong focus on reliability.',
    heroImage: '/products/power-station/hero.png',
    gallery: [
      '/products/power-station/hero.png',
      '/products/power-station/alternate.png',
      '/products/power-station/detail.png',
      '/products/power-station/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Capacity', value: '2048 Wh' },
      { label: 'AC Output', value: '2200W Peak' },
      { label: 'Ports', value: '13 Outputs' },
      { label: 'Charge Time', value: '1.8h Full Charge' },
    ],
    features: [
      'Useful for backup and travel',
      'Strong feature set for off-grid power',
      'Good hero product for broader campaigns',
      'Clean, technical presentation',
    ],
  },
  {
    slug: 'power-station-alternate',
    categorySlug: 'power-station',
    name: 'Power Station Alternate',
    tagline: 'A different angle on backup power.',
    description: 'A secondary visual showing the portable power station from another angle for campaigns and catalog pages.',
    heroImage: '/products/power-station/alternate.png',
    gallery: [
      '/products/power-station/alternate.png',
      '/products/power-station/hero.png',
      '/products/power-station/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'View', value: 'Alternate Angle' },
      { label: 'Tone', value: 'Technical' },
      { label: 'Use', value: 'Catalog' },
      { label: 'Audience', value: 'Power Users' },
    ],
    features: [
      'Works for product lineup sections',
      'Useful when you need a second visual',
      'Keeps the technical look consistent',
      'Adds variety to the category page',
    ],
  },
  {
    slug: 'power-station-detail',
    categorySlug: 'power-station',
    name: 'Power Station Detail',
    tagline: 'Closer looks at the hardware.',
    description: 'A detail-heavy page highlighting ports, finish, and component layout for deeper product browsing.',
    heroImage: '/products/power-station/detail.png',
    gallery: [
      '/products/power-station/detail.png',
      '/products/power-station/hero.png',
      '/products/power-station/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Focus', value: 'Ports' },
      { label: 'Layout', value: 'Front Panel' },
      { label: 'Use', value: 'Specs Page' },
      { label: 'Style', value: 'Detail' },
    ],
    features: [
      'Good for spec-driven product pages',
      'Shows build quality and layout',
      'Pairs well with technical bullet points',
      'Designed for closer inspection',
    ],
  },
  {
    slug: 'power-station-in-the-field',
    categorySlug: 'power-station',
    name: 'Power Station In the Field',
    tagline: 'Power wherever the job takes you.',
    description: 'Lifestyle imagery for showing the station in real-world scenarios like travel, outdoor work, or backup use.',
    heroImage: '/products/power-station/lifestyle.png',
    gallery: [
      '/products/power-station/lifestyle.png',
      '/products/power-station/hero.png',
      '/products/power-station/alternate.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Context', value: 'Field Use' },
      { label: 'Mood', value: 'Reliable' },
      { label: 'Audience', value: 'Travel / Backup' },
      { label: 'Format', value: 'Lifestyle' },
    ],
    features: [
      'Great for customer imagination',
      'Shows scale and portability in action',
      'Useful for brand storytelling',
      'Balances technical and human appeal',
    ],
  },
  {
    slug: '140w-gan-adapter',
    categorySlug: 'power-adapter',
    name: '140W GaN Adapter',
    tagline: 'Maximum watts. Minimum footprint.',
    description: 'A compact GaN charger for fast, efficient charging across laptop and mobile devices.',
    heroImage: '/products/power-adapter/hero.png',
    gallery: [
      '/products/power-adapter/hero.png',
      '/products/power-adapter/alternate.png',
      '/products/power-adapter/detail.png',
      '/products/power-adapter/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Max Output', value: '140W' },
      { label: 'Technology', value: 'GaN III' },
      { label: 'Ports', value: '3 USB-C + 1 USB-A' },
      { label: 'Protocol', value: 'PD 3.1 / PPS' },
    ],
    features: [
      'Made for powerful everyday charging',
      'Small body with a premium look',
      'Useful for laptop and phone users',
      'Strong page hero for accessories',
    ],
  },
  {
    slug: 'adapter-alternate-shot',
    categorySlug: 'power-adapter',
    name: 'Adapter Alternate Shot',
    tagline: 'A second angle for the same compact power.',
    description: 'Alternate visual treatment for product catalog layouts, ads, and comparison sections.',
    heroImage: '/products/power-adapter/alternate.png',
    gallery: [
      '/products/power-adapter/alternate.png',
      '/products/power-adapter/hero.png',
      '/products/power-adapter/detail.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'View', value: 'Alternate Angle' },
      { label: 'Style', value: 'Minimal' },
      { label: 'Use', value: 'Catalog' },
      { label: 'Audience', value: 'Tech Buyers' },
    ],
    features: [
      'Good for side-by-side product listings',
      'Maintains a consistent visual system',
      'Useful when you need supporting visuals',
      'Highlights clean industrial design',
    ],
  },
  {
    slug: 'adapter-close-up-detail',
    categorySlug: 'power-adapter',
    name: 'Adapter Close-up Detail',
    tagline: 'See the finish and ports up close.',
    description: 'A focused product view for showing the adapter ports, edges, and build details clearly.',
    heroImage: '/products/power-adapter/detail.png',
    gallery: [
      '/products/power-adapter/detail.png',
      '/products/power-adapter/hero.png',
      '/products/power-adapter/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Focus', value: 'Ports & Finish' },
      { label: 'Layout', value: 'Close-up' },
      { label: 'Use', value: 'Detail Page' },
      { label: 'Tone', value: 'Technical' },
    ],
    features: [
      'Works well for product detail sections',
      'Great for showing charging ports clearly',
      'Useful in feature-rich landing pages',
      'Supports conversion with clarity',
    ],
  },
  {
    slug: 'adapter-daily-carry',
    categorySlug: 'power-adapter',
    name: 'Adapter Daily Carry',
    tagline: 'The charger you actually keep with you.',
    description: 'Lifestyle imagery that frames the adapter as a practical everyday carry item.',
    heroImage: '/products/power-adapter/lifestyle.png',
    gallery: [
      '/products/power-adapter/lifestyle.png',
      '/products/power-adapter/hero.png',
      '/products/power-adapter/alternate.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Context', value: 'Daily Carry' },
      { label: 'Mood', value: 'Practical' },
      { label: 'Audience', value: 'Students / Pros' },
      { label: 'Format', value: 'Lifestyle' },
    ],
    features: [
      'Helps customers picture real use',
      'Great for lifestyle-focused campaigns',
      'Highlights portability and convenience',
      'Adds warmth to a technical product',
    ],
  },
  {
    slug: '20000mah-power-bank',
    categorySlug: 'power-bank',
    name: '20000mAh Power Bank',
    tagline: 'Reliable all-day backup.',
    description: 'A dependable high-capacity power bank for long days, travel, and backup charging.',
    heroImage: '/products/power-bank/hero.png',
    gallery: [
      '/products/power-bank/hero.png',
      '/products/power-bank/fast-hero.png',
      '/products/power-bank/slim-hero.png',
      '/products/power-bank/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Capacity', value: '20,000mAh' },
      { label: 'Charging', value: 'Fast Charge' },
      { label: 'Form', value: 'Portable' },
      { label: 'Use', value: 'Daily Backup' },
    ],
    features: [
      'Great balance of capacity and portability',
      'Strong choice for travel and daily carry',
      'Clean hero presentation for ecommerce',
      'Works across consumer and B2B pages',
    ],
  },
  {
    slug: '20000mah-slim-power-bank',
    categorySlug: 'power-bank',
    name: '20000mAh Slim Power Bank',
    tagline: 'Big capacity, slimmer profile.',
    description: 'A thinner form factor for users who want power without a bulky feel.',
    heroImage: '/products/power-bank/slim-hero.png',
    gallery: [
      '/products/power-bank/slim-hero.png',
      '/products/power-bank/hero.png',
      '/products/power-bank/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Capacity', value: '20,000mAh' },
      { label: 'Profile', value: 'Slim' },
      { label: 'Portability', value: 'Pocket Friendly' },
      { label: 'Use', value: 'Everyday Carry' },
    ],
    features: [
      'Slim shape for easier carrying',
      'Great for users who value portability',
      'Good companion product for bundles',
      'Visual fit for modern ecommerce layouts',
    ],
  },
  {
    slug: '25000mah-built-in-cables',
    categorySlug: 'power-bank',
    name: '25000mAh Power Bank with Built-In Cables',
    tagline: 'Carry fewer cables. Charge more devices.',
    description: 'An all-in-one power bank built for convenience, with integrated cables for fast access.',
    heroImage: '/products/power-bank/builtin-hero.png',
    gallery: [
      '/products/power-bank/builtin-hero.png',
      '/products/power-bank/hero.png',
      '/products/power-bank/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Capacity', value: '25,000mAh' },
      { label: 'Feature', value: 'Built-In Cables' },
      { label: 'Charging', value: 'Fast Charge' },
      { label: 'Use', value: 'Travel Ready' },
    ],
    features: [
      'Simplifies carry and cable management',
      'Ideal for travel and emergency use',
      'Great for convenience-led marketing',
      'Practical product story for conversion',
    ],
  },
  {
    slug: '24000mah-fast-charge-power-bank',
    categorySlug: 'power-bank',
    name: '24000mAh Fast Charge Power Bank',
    tagline: 'High capacity for longer trips.',
    description: 'A high-output power bank focused on endurance, speed, and staying powered for longer.',
    heroImage: '/products/power-bank/fast-hero.png',
    gallery: [
      '/products/power-bank/fast-hero.png',
      '/products/power-bank/hero.png',
      '/products/power-bank/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Capacity', value: '24,000mAh' },
      { label: 'Charge Mode', value: 'Fast Charge' },
      { label: 'Output Focus', value: 'High Power' },
      { label: 'Use', value: 'Long Trips' },
    ],
    features: [
      'Good for users with heavier charging needs',
      'Designed around high-capacity use',
      'Useful as a premium power bank option',
      'Works well in spec-led product layouts',
    ],
  },
  {
    slug: 'anc-earbuds',
    categorySlug: 'earbuds',
    name: 'ANC Earbuds',
    tagline: 'Focused listening for everyday life.',
    description: 'Noise-aware earbuds designed for commutes, calls, and everyday music use.',
    heroImage: '/products/earbuds/hero.png',
    gallery: [
      '/products/earbuds/hero.png',
      '/products/earbuds/alternate.png',
      '/products/earbuds/detail.png',
      '/products/earbuds/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Audio Mode', value: 'ANC' },
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Use', value: 'Commute / Calls' },
      { label: 'Style', value: 'Compact' },
    ],
    features: [
      'Good for work, travel, and daily use',
      'Compact styling that feels premium',
      'Fits a wide range of lifestyles',
      'Strong hero images for landing pages',
    ],
  },
  {
    slug: 'earbuds-alternate-angle',
    categorySlug: 'earbuds',
    name: 'Earbuds Alternate Angle',
    tagline: 'A second look at the design.',
    description: 'An alternate view of the earbuds that helps show shape, case, and visual balance.',
    heroImage: '/products/earbuds/alternate.png',
    gallery: [
      '/products/earbuds/alternate.png',
      '/products/earbuds/hero.png',
      '/products/earbuds/detail.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'View', value: 'Alternate Angle' },
      { label: 'Use', value: 'Catalog' },
      { label: 'Mood', value: 'Modern' },
      { label: 'Audience', value: 'Audio Buyers' },
    ],
    features: [
      'Great for comparison and lineup pages',
      'Adds variety to product storytelling',
      'Keeps visual identity consistent',
      'Useful for carousel-based browsing',
    ],
  },
  {
    slug: 'earbuds-close-up-detail',
    categorySlug: 'earbuds',
    name: 'Earbuds Close-up Detail',
    tagline: 'See the finish and form up close.',
    description: 'A detail-rich product view for highlighting materials, fit, and controls.',
    heroImage: '/products/earbuds/detail.png',
    gallery: [
      '/products/earbuds/detail.png',
      '/products/earbuds/hero.png',
      '/products/earbuds/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Focus', value: 'Detail View' },
      { label: 'Controls', value: 'Touch Ready' },
      { label: 'Use', value: 'Specs Page' },
      { label: 'Style', value: 'Close-up' },
    ],
    features: [
      'Helps explain build quality visually',
      'Great for feature callouts',
      'Supports high-intent purchase pages',
      'Pairs well with spec cards',
    ],
  },
  {
    slug: 'earbuds-everyday-carry',
    categorySlug: 'earbuds',
    name: 'Earbuds Everyday Carry',
    tagline: 'Built for movement, commutes, and calls.',
    description: 'Lifestyle imagery that shows the earbuds in real use so customers can picture ownership.',
    heroImage: '/products/earbuds/lifestyle.png',
    gallery: [
      '/products/earbuds/lifestyle.png',
      '/products/earbuds/hero.png',
      '/products/earbuds/alternate.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Context', value: 'Lifestyle' },
      { label: 'Mood', value: 'Everyday' },
      { label: 'Audience', value: 'On-the-go Users' },
      { label: 'Format', value: 'Hero Scene' },
    ],
    features: [
      'Strong for ads and social creatives',
      'Makes the earbuds feel more relatable',
      'Useful for storytelling and conversion',
      'Keeps the product active and human',
    ],
  },
  {
    slug: '100w-fast-charging-cable',
    categorySlug: 'cables',
    name: '100W Fast Charging Cable',
    tagline: 'Fast, simple, and dependable.',
    description: 'A clean everyday cable built for high-speed charging and broad compatibility.',
    heroImage: '/products/cables/hero.png',
    gallery: [
      '/products/cables/hero.png',
      '/products/cables/3in1-hero.png',
      '/products/cables/typec-hero.png',
      '/products/cables/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Power', value: '100W' },
      { label: 'Use', value: 'Fast Charging' },
      { label: 'Type', value: 'USB-C' },
      { label: 'Audience', value: 'Daily Users' },
    ],
    features: [
      'Simple product story for accessories pages',
      'Reliable charging-focused design',
      'Works well as a hero cable listing',
      'Good for bundle and upsell sections',
    ],
  },
  {
    slug: '3-in-1-cable',
    categorySlug: 'cables',
    name: '3-in-1 Cable',
    tagline: 'One cable, multiple devices.',
    description: 'A versatile cable solution for mixed-device users and multi-device charging setups.',
    heroImage: '/products/cables/3in1-hero.png',
    gallery: [
      '/products/cables/3in1-hero.png',
      '/products/cables/hero.png',
      '/products/cables/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Format', value: '3-in-1' },
      { label: 'Use', value: 'Multi-device' },
      { label: 'Style', value: 'Versatile' },
      { label: 'Audience', value: 'Everyday Carry' },
    ],
    features: [
      'Ideal for users with mixed devices',
      'Helpful for travel and daily carry',
      'Easy to understand in product grids',
      'Strong accessory-line storytelling',
    ],
  },
  {
    slug: 'type-c-smart-display',
    categorySlug: 'cables',
    name: 'Type-C Smart Display Cable',
    tagline: 'Charging status at a glance.',
    description: 'A cable with a smart display for users who want more feedback and a more premium feel.',
    heroImage: '/products/cables/typec-hero.png',
    gallery: [
      '/products/cables/typec-hero.png',
      '/products/cables/hero.png',
      '/products/cables/lifestyle.png',
    ],
    accentColor: '#3F87FE',
    specs: [
      { label: 'Type', value: 'USB-C' },
      { label: 'Display', value: 'Smart Screen' },
      { label: 'Use', value: 'Charging Feedback' },
      { label: 'Audience', value: 'Power Users' },
    ],
    features: [
      'Premium feel for accessory pages',
      'Clear visual differentiation from basic cables',
      'Great for specs-heavy comparisons',
      'Useful for technical audiences',
    ],
  },
  {
    slug: 'mop-vacuum-robot',
    categorySlug: 'cleaning',
    name: 'Mop & Vacuum Robot',
    tagline: 'Let the floor do itself.',
    description: 'An automated cleaning solution for daily dust, spills, and routine floor maintenance.',
    heroImage: '/products/cleaning/hero.png',
    gallery: [
      '/products/cleaning/hero.png',
      '/products/cleaning/glass-hero.png',
      '/products/cleaning/mop-hero.png',
      '/products/cleaning/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Function', value: 'Mop + Vacuum' },
      { label: 'Automation', value: 'Robot' },
      { label: 'Use', value: 'Floor Care' },
      { label: 'Style', value: 'Smart Home' },
    ],
    features: [
      'Strong for smart home product pages',
      'Makes home care look effortless',
      'Good hero product for cleaning category',
      'Simple messaging for customers',
    ],
  },
  {
    slug: 'glass-cleaner-robot',
    categorySlug: 'cleaning',
    name: 'Glass Cleaner Robot',
    tagline: 'For windows and hard-to-reach glass.',
    description: 'A specialized cleaning robot designed to tackle glass surfaces more safely and efficiently.',
    heroImage: '/products/cleaning/glass-hero.png',
    gallery: [
      '/products/cleaning/glass-hero.png',
      '/products/cleaning/hero.png',
      '/products/cleaning/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Surface', value: 'Glass' },
      { label: 'Format', value: 'Robot Cleaner' },
      { label: 'Use', value: 'Windows' },
      { label: 'Style', value: 'Specialized' },
    ],
    features: [
      'Great for specialty cleaning use cases',
      'Helps explain a specific job to customers',
      'Good fit for product comparison pages',
      'Adds variety inside the category',
    ],
  },
  {
    slug: 'mop-vacuum-classic',
    categorySlug: 'cleaning',
    name: 'Mop & Vacuum Classic',
    tagline: 'A straightforward cleaning companion.',
    description: 'A classic floor-cleaning configuration for customers who want simple and dependable performance.',
    heroImage: '/products/cleaning/mop-hero.png',
    gallery: [
      '/products/cleaning/mop-hero.png',
      '/products/cleaning/hero.png',
      '/products/cleaning/lifestyle.png',
    ],
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Function', value: 'Mop + Vacuum' },
      { label: 'Format', value: 'Classic' },
      { label: 'Use', value: 'Home Cleaning' },
      { label: 'Style', value: 'Practical' },
    ],
    features: [
      'Easy to understand for shoppers',
      'Good baseline product in the range',
      'Supports a clean and simple story',
      'Works well in category grids',
    ],
  },
  {
    slug: 'android-ai-box',
    categorySlug: 'car-accessories',
    name: 'Android AI Box',
    tagline: 'Upgrade your infotainment system.',
    description: 'A smart car accessory that adds more flexibility, apps, and usability to your dashboard.',
    heroImage: '/products/car-accessories/hero.png',
    gallery: [
      '/products/car-accessories/hero.png',
      '/products/car-accessories/cover-hero.png',
      '/products/car-accessories/jumpstart-hero.png',
      '/products/car-accessories/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Type', value: 'AI Box' },
      { label: 'Use', value: 'Car Infotainment' },
      { label: 'Style', value: 'Smart' },
      { label: 'Audience', value: 'Drivers' },
    ],
    features: [
      'Good for smarter in-car experiences',
      'Helps modernize the dashboard feel',
      'Strong hero image for the category',
      'Fits tech-focused automotive pages',
    ],
  },
  {
    slug: 'automatic-car-cover',
    categorySlug: 'car-accessories',
    name: 'Automatic Car Cover',
    tagline: 'Protection with less hassle.',
    description: 'An easy-to-present car cover solution that emphasizes convenience and vehicle protection.',
    heroImage: '/products/car-accessories/cover-hero.png',
    gallery: [
      '/products/car-accessories/cover-hero.png',
      '/products/car-accessories/hero.png',
      '/products/car-accessories/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Type', value: 'Auto Cover' },
      { label: 'Use', value: 'Protection' },
      { label: 'Style', value: 'Convenient' },
      { label: 'Audience', value: 'Car Owners' },
    ],
    features: [
      'Useful for premium protection messaging',
      'Good for practical automotive marketing',
      'Easy to understand and visualize',
      'Adds more depth to the catalog',
    ],
  },
  {
    slug: 'jump-starter-tyre-inflator',
    categorySlug: 'car-accessories',
    name: 'Jump Starter & Tyre Inflator',
    tagline: 'Emergency support for the road.',
    description: 'A compact roadside-support accessory for jump starting and tyre inflation on the move.',
    heroImage: '/products/car-accessories/jumpstart-hero.png',
    gallery: [
      '/products/car-accessories/jumpstart-hero.png',
      '/products/car-accessories/hero.png',
      '/products/car-accessories/lifestyle.png',
    ],
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Function', value: 'Jump Start + Inflate' },
      { label: 'Use', value: 'Road Safety' },
      { label: 'Format', value: 'Portable' },
      { label: 'Audience', value: 'Drivers' },
    ],
    features: [
      'Strong emergency-use product story',
      'Very practical for road safety pages',
      'Great for trust-building catalog copy',
      'Useful as a utility-focused hero item',
    ],
  },
];

export const spotlightProducts: SpotlightProduct[] = [
  {
    id: 'scooter',
    name: 'Dual Motor E-Scooter',
    tagline: 'Built for roads that push back.',
    heroImage: '/products/scooter/1hero.png',
    accentColor: '#3F87FE',
    specs: [
      { label: 'Drive System', value: 'Dual Motor' },
      { label: 'Terrain', value: 'Off-Road Tires' },
      { label: 'Frame', value: 'Foldable Alloy' },
      { label: 'Range', value: 'Up to 65 km' },
    ],
    ctaLink: '/products/scooter/dual-motor-e-scooter',
  },
  {
    id: 'speaker',
    name: 'RGB Speaker',
    tagline: 'Sound that moves. Light that breathes.',
    heroImage: '/products/speaker/hero.png',
    accentColor: '#7B5CFF',
    specs: [
      { label: 'Sound Stage', value: '360° Surround' },
      { label: 'RGB Ring', value: '16M Colour' },
      { label: 'Battery', value: '24-Hour Playback' },
      { label: 'Connectivity', value: 'Bluetooth 5.3' },
    ],
    ctaLink: '/products/speaker/rgb-speaker',
  },
  {
    id: 'power-station',
    name: 'Portable Power Station',
    tagline: 'The grid, untethered.',
    heroImage: '/products/power-station/hero.png',
    accentColor: '#3FE0FE',
    specs: [
      { label: 'Capacity', value: '2048 Wh' },
      { label: 'AC Output', value: '2200W Peak' },
      { label: 'Ports', value: '13 Outputs' },
      { label: 'Charge Time', value: '1.8h Full Charge' },
    ],
    ctaLink: '/products/power-station/portable-power-station',
  },
  {
    id: 'power-adapter',
    name: '140W GaN Adapter',
    tagline: 'Maximum watts. Minimum footprint.',
    heroImage: '/products/power-adapter/hero.png',
    accentColor: '#3F87FE',
    specs: [
      { label: 'Max Output', value: '140W' },
      { label: 'Technology', value: 'GaN III' },
      { label: 'Ports', value: '3 USB-C + 1 USB-A' },
      { label: 'Protocol', value: 'PD 3.1 / PPS' },
    ],
    ctaLink: '/products/power-adapter/140w-gan-adapter',
  },
];

export function getCategoryProducts(categorySlug: string): CatalogProduct[] {
  return catalogProducts.filter((product) => product.categorySlug === categorySlug);
}

export function getProduct(categorySlug: string, productSlug: string): CatalogProduct | undefined {
  return catalogProducts.find(
    (product) => product.categorySlug === categorySlug && product.slug === productSlug
  );
}
